import type { APIRoute } from "astro";
import { projects } from "../data/projects";
import { stats } from "../data/stats";

interface Article {
  url: string;
  frontmatter: {
    title: string;
    description: string;
    date: string;
    readingTime: string;
  };
}

const articles = Object.values(
  import.meta.glob<Article>("./writing/*.md", { eager: true }),
).sort(
  (a, b) =>
    new Date(b.frontmatter.date).valueOf() -
    new Date(a.frontmatter.date).valueOf(),
);

/* The ref parameter credits this site in a referral log, which a file written for machines has no use for. */
const clean = (href: string) => href.split("?")[0];

/* Markdown pages report a url without the trailing slash the built site serves. */
const withSlash = (path: string) =>
  path.startsWith("/writing/") && !path.endsWith("/") ? `${path}/` : path;

const absolute = (href: string, site: URL) =>
  href.startsWith("http") ? clean(href) : new URL(withSlash(href), site).href;

const entry = (title: string, href: string, note: string, site: URL) =>
  `- [${title}](${absolute(href, site)}): ${note}`;

const year = (date: string) => new Date(date).getFullYear();

export const GET: APIRoute = ({ site }) => {
  const base = site!;
  const reach = stats
    .map((stat) => `${stat.value} ${stat.label.toLowerCase()}`)
    .join(", ");

  const sections = [
    `# Edvin Lindén`,
    ``,
    `> Edvin Lindén builds small apps for iPhone and iPad. Every app is free, carries no advertising and asks for no account. Across all of them: ${reach}.`,
    ``,
    `Edvin is a product leader at Fortnox in Sweden and writes now and then about product management and about building apps on the side. This site is the home of those apps and that writing. Nothing here is behind a login or a paywall, and no page is generated by a language model.`,
    ``,
    `## Apps`,
    ``,
    ...projects.flatMap((project) => {
      const badge = project.badge ? `, ${project.badge.toLowerCase()}` : "";
      const note = `${project.summary} (${project.years.replace(/\s+/g, " ").trim()}${badge})`;
      const bullet = entry(project.title, project.href, note, base);
      return project.href === "/sudoku/"
        ? [
            bullet,
            entry(
              "Sudoku, the whole page as markdown",
              "/sudoku.md",
              "Features, languages, App Store rating, customer reviews and the full FAQ in one plain-text file",
              base,
            ),
          ]
        : [bullet];
    }),
    ``,
    `## Writing`,
    ``,
    ...articles.map((article) =>
      entry(
        article.frontmatter.title,
        article.url,
        `${article.frontmatter.description} (${year(article.frontmatter.date)}, ${article.frontmatter.readingTime})`,
        base,
      ),
    ),
    ``,
    `## About`,
    ``,
    entry(
      "About Edvin Lindén",
      "/about/",
      "What Edvin does for work, what he writes about and the side projects he has shipped",
      base,
    ),
    entry(
      "Contact",
      "mailto:hello@edvinlinden.se",
      "Email is the only way to get in touch",
      base,
    ),
    ``,
    `## Optional`,
    ``,
    entry(
      "Privacy policy for this site",
      "/privacy/",
      "What the site measures and how to switch it off",
      base,
    ),
    entry(
      "Privacy policy for Sudoku",
      "/sudoku/privacy/",
      "What the Sudoku app collects, which is anonymous usage data and nothing else",
      base,
    ),
    entry(
      "Privacy policy for Box Timer",
      "https://boxtimer.app/privacy/",
      "What the Box Timer app collects",
      base,
    ),
    entry(
      "Privacy policy for The Impossible Safe",
      "/the-impossible-safe/privacy/",
      "What The Impossible Safe collects",
      base,
    ),
    entry("RSS feed", "/rss.xml", "New writing as it is published", base),
    entry("Sitemap", "/sitemap-index.xml", "Every page on the site", base),
    ``,
  ];

  return new Response(sections.join("\n"), {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
};
